
```{r}
set.seed(40601)
library(tidyverse)
```

```{r}
# GENERATE "TRUE" DATE PER FUNK ET AL. 2011
gen_data <- function(n){
  
  # GENERATE IVs
z1 <- rnorm(n, mean = 0, sd = 1)
z2 <- rnorm(n, mean = 0, sd = 1)
z3 <- rbinom(n, size = 1, prob = 0.3)

# GENERATE EXPOSURE AS A FUNCTION OF IVs
# Set betas for true model
b0_0 = 1.5
b1_0 = 1
b2_0 = -2
b3_0 = 1

# Calculate true propensity scores (logit)
ps <- (1 + exp(-1 * (b0_0 + b1_0*z1 + b2_0*z2 + b3_0*z3)))^(-1)

# Calculate exposure
d <- ifelse((ps + runif(n, min = 0, max = 1)) < 0.91, 1, 0)

# GENERATE TRUE OUTCOMES
b4_0 <- 2
z4 <- rnorm(n, mean = 0, sd = 1)
y <- b1_0*z1 + b3_0*z3 + b4_0*z4

# TRUE DATA
data <- tibble(z1, z2, z3, d, ps, y)
return(data)
}
```

```{r}
# SECNARIO 1
# Both models correctly specified: gg

gg_ate <- function(data){
  # Fit correct outcome regression models within exposure groups
  mod_t <- lm(y ~ z1 + z3, data = data %>% filter(d == 1))
  mod_c <- lm(y ~ z1 + z3, data = data %>% filter(d == 0))
  
  # Predict outcomes for everyone
  data <- data %>% mutate(yhat1 = predict(mod_t, data))
  data <- data %>% mutate(yhat0 = predict(mod_c, data))
  
  # Fit correct propensity score model
  ps_mod <- glm(d ~ z1 + z2 + z3, data = data, family = 'binomial')
  
  # Predict propensity scores
  data <- data %>% mutate(ps_hat = predict(ps_mod, data, type = 'response'))
  
  # Compute doubly robust estimates
  data <- data %>% mutate(dr1 = 
                            ifelse(d == 1, 
                                   ((y / ps_hat) - ((yhat1 * (1 - ps_hat)) / (ps_hat))),
                                   (yhat1)),
                          dr0 =
                            ifelse(d == 1,
                                   (yhat0),
                                   ((y / (1 - ps_hat) - ((yhat0 * ps_hat) / (1 - ps_hat))))))
  
  # Estimate ATE
  return(mean(data$dr1) - mean(data$dr0))
}
```

```{r}
# SCENARIO 2
# Bad outcome regression model, good propensity score model: bg

bg_ate <- function(data){
  # Misspecify outcome regression models within exposure groups (omit z3)
  mod_t <- lm(y ~ z1, data = data %>% filter(d == 1))
  mod_c <- lm(y ~ z1, data = data %>% filter(d == 0))
  
  # Predict outcomes for everyone
  data <- data %>% mutate(yhat1 = predict(mod_t, data))
  data <- data %>% mutate(yhat0 = predict(mod_c, data))
  
  # Fit correct propensity score model
  ps_mod <- glm(d ~ z1 + z2 + z3, data = data, family = 'binomial')
  
  # Predict propensity scores
  data <- data %>% mutate(ps_hat = predict(ps_mod, data, type = 'response'))
  
  # Compute doubly robust estimates
  data <- data %>% mutate(dr1 = 
                            ifelse(d == 1, 
                                   ((y / ps_hat) - ((yhat1 * (1 - ps_hat)) / (ps_hat))),
                                   (yhat1)),
                          dr0 =
                            ifelse(d == 1,
                                   (yhat0),
                                   ((y / (1 - ps_hat) - ((yhat0 * ps_hat) / (1 - ps_hat))))))
  
  # Estimate ATE
  return(mean(data$dr1) - mean(data$dr0))
}
```

```{r}
# SCENARIO 3  
# Good outcome regression model, bad propensity score model: gb

gb_ate <- function(data){
  # Fit correct outcome regression models within exposure groups
  mod_t <- lm(y ~ z1 + z3, data = data %>% filter(d == 1))
  mod_c <- lm(y ~ z1 + z3, data = data %>% filter(d == 0))
  
  # Predict outcomes for everyone
  data <- data %>% mutate(yhat1 = predict(mod_t, data))
  data <- data %>% mutate(yhat0 = predict(mod_c, data))
  
  # Misspecify propensity score model (omit z3)
  ps_mod <- glm(d ~ z1 + z2, data = data, family = 'binomial')
  
  # Predict propensity scores
  data <- data %>% mutate(ps_hat = predict(ps_mod, data, type = 'response'))
  
  # Compute doubly robust estimates
  data <- data %>% mutate(dr1 = 
                            ifelse(d == 1, 
                                   ((y / ps_hat) - ((yhat1 * (1 - ps_hat)) / (ps_hat))),
                                   (yhat1)),
                          dr0 =
                            ifelse(d == 1,
                                   (yhat0),
                                   ((y / (1 - ps_hat) - ((yhat0 * ps_hat) / (1 - ps_hat))))))
  
  # Estimate ATE
  return(mean(data$dr1) - mean(data$dr0))
}
```


```{r}
# GENERATE ATES
gen_ates <- function(n){
  gg <- rep(NA, length(n))
  bg <- rep(NA, length(n))
  gb <- rep(NA, length(n))
  for(i in 1:1000){
    data <- gen_data(n)
    gg[i] <- gg_ate(data)
    bg[i] <- bg_ate(data)
    gb[i] <- gb_ate(data)
    
  }
  gg_avg <- mean(gg)
  bg_avg <- mean(bg)
  gb_avg <- mean(gb)
  return(c(gg_avg, bg_avg, gb_avg))
}
```

```{r}
gen_ates(100)
```

```{r}
gen_ates(500)
```

```{r}
gen_ates(1000)
```

```{r}
gen_ates(2000)
```

```{r}
gen_ates(10000)
```

